import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import CarouselComponent from '../components/carousel'
import CardComponent from '../components/cardComponent'
import NavHeader from '../components/Header'


const Home: NextPage = () => {

  
  return (
    <div>
      <NavHeader/>
      
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <CarouselComponent />

        <div className={styles.homeProducts}>
          <CardComponent />
          <CardComponent />
          <CardComponent />
        </div>
      </div>
     
    </div>
  )
}

export default Home
